
development:
  adapter: postgresql
  database: library_development
  username: joes
  password: test
  host: localhost
test:
  adapter: postgresql
  database: library_test
  username: joes
  password: test
  host: localhost
production:
  adapter: postgresql
  database: library_production
  username: joes 
  password: test
  host: localhost
